### ISSUE TITLE
Unable to Export Database using last 161.6374.0 SqlPackage

### ISSUE THREAD

**Issue by Mark7Anderson** [microsoft/DacFx#208] opened 2023-01-25 17:31 UTC
- SqlPackage or DacFx Version:
- .NET Framework (Windows-only) or .NET Core:
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1.I am getting below error while importing Database using last 161.6374.0 SqlPackage and the script used to export the database is added below.

Script:
SqlPackage.exe /a:export /ssn:localhost /sdn:AxDB_UAT /tf:D:\ConfigDB\AxDBGoldenConfig.bacpac /p:CommandTimeout=1200 /p:VerifyFullTextDocumentTypesSupported=false

Error:
C:\Temp\sqlpackage-win7-x64-en-16.1.6374.0>SqlPackage.exe /a:export /ssn:localhost /sdn:AxDB_UAT /tf:D:\ConfigDB\AxDBGoldenConfig.bacpac /p:CommandTimeout=1200 /p:VerifyFullTextDocumentTypesSupported=false
Connecting to database 'AxDB_UAT' on server 'localhost'.
*** Changes to connection setting default values were incorporated in a recent release.  More information is available at https://aka.ms/dacfx-connection
*** Error exporting database:Could not connect to database server.
Changes to connection setting default values were incorporated in a recent release.  More information is available at https://aka.ms/dacfx-connection
A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
The certificate chain was issued by an authority that is not trusted.
*** The settings for connection encryption or server certificate trust may lead to connection failure if the server is not properly configured.
Time elapsed 0:00:41.72

2. can any one suggest the solution for this ?
![Export](https://user-images.githubusercontent.com/123557221/214638112-8695231c-0818-4462-91a1-2467fa01874f.jpg)

**Did this occur in prior versions?  If not - which version(s) did it work in?** No it was working in 19.2 SqlPackage and below versions.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by llali** [comment] 2023-01-25 22:00
The details are provided in the error message 👍  Changes to connection setting default values were incorporated in a recent release. More information is available at https://aka.ms/dacfx-connection
*** Error exporting database:Could not connect to database server.
Changes to connection setting default values were incorporated in a recent release. More information is available at https://aka.ms/dacfx-connection

Please set Encrypt in the connection string to false

**Comment by llali** [comment] 2023-01-25 22:00
closing as by design

**Closed by llali** 2023-01-25 22:00 UTC
Labels: bug
