### ISSUE TITLE
Error SQL72014 on Publish dacpac to Synapse Serverless

### ISSUE THREAD

**Issue by SaschaProdware** [microsoft/DacFx#246] opened 2023-03-27 15:24 UTC
- SqlPackage or DacFx Version: 16.1.8089.0
- .NET Framework (Windows-only) or .NET Core: 
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Export: 

.\SqlPackage.exe /Action:Extract /TargetFile:"C:\Users\firstname.lastname\Documents\Serverlessbackup\DatabaseBI_Dev.dacpac" /SourceConnectionString:"Authentication=Active Directory Interactive;Server=tcp:xxxxxxxxxxx-synapse-ondemand.sql.azuresynapse.net,1433;Initial Catalog=DatabaseBI_DEV;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

Connecting to database 'DatabaseBI_DEV' on server 'tcp:xxxxxxx-synapse-ondemand.sql.azuresynapse.net,1433'.
Extracting schema
Extracting schema from database
*** **Error validating element** [dbo].[CustTable]: Incorrect syntax near '{"READ_OPTIONS":["ALLOW_INCONSISTENT_READS"] }'.
(...)
*** Error validating element [dbo].[BIDateDimensionValue]: Incorrect syntax near '{"READ_OPTIONS":["ALLOW_INCONSISTENT_READS"] }'.
*** Error validating element [dbo].[BIDateDimension]: Incorrect syntax near '{"READ_OPTIONS":["ALLOW_INCONSISTENT_READS"] }'.
Resolving references in schema model
Validating schema model for data package
Validating schema
Successfully extracted database and saved it to file 'C:\Users\firstname.lastname\Documents\Serverlessbackup\DatabaseBI_Dev.dacpac'.
Changes to connection setting default values were incorporated in a recent release.  More information is available at https://aka.ms/dacfx-connection

2. Publish

Publishing to database 'DatabaseBI_Backup20230327' on server 'tcp:xxxxxxxxxx-synapse-ondemand.sql.azuresynapse.net,1433'.
Initializing deployment (Start)
Initializing deployment (Complete)
Analyzing deployment plan (Start)
Analyzing deployment plan (Complete)
Updating database (Start)
Creating database NexusBI_Backup20230327...
Creating Master Key Master Key...
Creating Database Scoped Credential [dynamics365_financeandoperations_tn_prod]...
Creating Database Scoped Credential [dynamics365_financeandoperations_tn_prod_copy]...
Creating View [dbo].[LogisticsPostalAddress]...
An error occurred while the batch was being executed.
Updating database (Failed)
.\sqlpackage.exe : *** Could not deploy package.
At C:\Users\firstname.lastname\Documents\PowerShell\PublishSQL.ps1:6 char:1
+ .\sqlpackage.exe /Action:Publish /SourceFile:"C:\Users\firstname.lastname...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (*** Could not deploy package.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
**Error SQL72014** : Framework Microsoft SqlClient Data Provider: Msg 12703, Level 16, State 2, Procedure LogisticsPostalAddress, Line 4 Referenced external data source 
"dynamics365_financeandoperations_tn_prod_copy_EDS" not found.
Error SQL72045: Script execution error.  The executed script:
CREATE VIEW [dbo].[LogisticsPostalAddress]
AS
SELECT cast(r.filepath(1) AS VARCHAR(100)) AS [$FileName]
	, _SysRowId
	, LSN
	, LastProcessedChange_DateTime
	, DataLakeModified_DateTime
	, RECID
	, ADDRESS
	, APARTMENT_RU
	, BUILDING_RU
	, BUILDINGCOMPLIMENT
	, CITY
	, CITYRECID
	, COUNTRYREGIONID
	, COUNTY
	, DISTRICT
	, DISTRICTNAME
	, FLATID_RU
	, HOUSEID_RU
	, ISPRIVATE
	, LATITUDE
	, LOCATION
	, LONGITUDE
	, POSTBOX
	, PRIVATEFORPARTY
	, STATE
	, STREET
	, STREETID_RU
	, STREETNUMBER
	, TIMEZONE
	, VALIDFROM
	, VALIDFROMTZID
	, VALIDTO
	, VALIDTOTZID
	, ZIPCODE
	, ZIPCODERECID
	, CITYKANA_JP
	, STREETKANA_JP
	, PARTITION
	, RECVERSION
	, MODIFIEDDATETIME
	, MODIFIEDBY
	, STEADID_RU
	, GLOBALLOCALIZATIONNUMBER
	, ISSIMPLIFIEDADDRESS_RU
	, CHANNELREFERENCEID
	, SETTLEMENTRECID
	, LOCALITYRECID
FROM OPENROWSET(BULK 'Tables/Common/GAB/Main/LogisticsPostalAddress/*.csv', FORMAT = 'CSV', PARSER_VERSION = '2.0', DATA_SOURCE = 'dynamics365_financeandoperations_tn

3. I can Query this View (SELECT * FROM [dbo].[LogisticsPostalAddress]) successfully 
4. I can DROP and CREATE this View

/****** Object:  View [dbo].[LogisticsPostalAddress]    Script Date: 3/27/2023 3:19:16 PM ******/
DROP VIEW [dbo].[LogisticsPostalAddress]
GO

/****** Object:  View [dbo].[LogisticsPostalAddress]    Script Date: 3/27/2023 3:19:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[LogisticsPostalAddress]
AS
SELECT cast(r.filepath(1) AS VARCHAR(100)) AS [$FileName]
	, _SysRowId
	, LSN
	, LastProcessedChange_DateTime
	, DataLakeModified_DateTime
	, RECID
	, ADDRESS
	, APARTMENT_RU
	, BUILDING_RU
	, BUILDINGCOMPLIMENT
	, CITY
	, CITYRECID
	, COUNTRYREGIONID
	, COUNTY
	, DISTRICT
	, DISTRICTNAME
	, FLATID_RU
	, HOUSEID_RU
	, ISPRIVATE
	, LATITUDE
	, LOCATION
	, LONGITUDE
	, POSTBOX
	, PRIVATEFORPARTY
	, STATE
	, STREET
	, STREETID_RU
	, STREETNUMBER
	, TIMEZONE
	, VALIDFROM
	, VALIDFROMTZID
	, VALIDTO
	, VALIDTOTZID
	, ZIPCODE
	, ZIPCODERECID
	, CITYKANA_JP
	, STREETKANA_JP
	, PARTITION
	, RECVERSION
	, MODIFIEDDATETIME
	, MODIFIEDBY
	, STEADID_RU
	, GLOBALLOCALIZATIONNUMBER
	, ISSIMPLIFIEDADDRESS_RU
	, CHANNELREFERENCEID
	, SETTLEMENTRECID
	, LOCALITYRECID
FROM OPENROWSET(BULK 'Tables/Common/GAB/Main/LogisticsPostalAddress/*.csv', FORMAT = 'CSV', PARSER_VERSION = '2.0', DATA_SOURCE = 'dynamics365_financeandoperations_tn_prod_copy_EDS', ROWSET_OPTIONS = '{"READ_OPTIONS":["ALLOW_INCONSISTENT_READS"] }') WITH (
		_SysRowId BIGINT
		, LSN NVARCHAR(60)
		, LastProcessedChange_DateTime DATETIME2
		, DataLakeModified_DateTime DATETIME2
		, RECID BIGINT
		, ADDRESS NVARCHAR(250)
		, APARTMENT_RU NVARCHAR(10)
		, BUILDING_RU NVARCHAR(10)
		, BUILDINGCOMPLIMENT NVARCHAR(60)
		, CITY NVARCHAR(60)
		, CITYRECID BIGINT
		, COUNTRYREGIONID NVARCHAR(10)
		, COUNTY NVARCHAR(30)
		, DISTRICT BIGINT
		, DISTRICTNAME NVARCHAR(60)
		, FLATID_RU BIGINT
		, HOUSEID_RU BIGINT
		, ISPRIVATE BIGINT
		, LATITUDE NUMERIC(32, 6)
		, LOCATION BIGINT
		, LONGITUDE NUMERIC(32, 6)
		, POSTBOX NVARCHAR(20)
		, PRIVATEFORPARTY BIGINT
		, STATE NVARCHAR(10)
		, STREET NVARCHAR(250)
		, STREETID_RU BIGINT
		, STREETNUMBER NVARCHAR(20)
		, TIMEZONE BIGINT
		, VALIDFROM DATETIME2
		, VALIDFROMTZID BIGINT
		, VALIDTO DATETIME2
		, VALIDTOTZID BIGINT
		, ZIPCODE NVARCHAR(10)
		, ZIPCODERECID BIGINT
		, CITYKANA_JP NVARCHAR(60)
		, STREETKANA_JP NVARCHAR(250)
		, PARTITION BIGINT
		, RECVERSION BIGINT
		, MODIFIEDDATETIME DATETIME2
		, MODIFIEDBY NVARCHAR(20)
		, STEADID_RU BIGINT
		, GLOBALLOCALIZATIONNUMBER NVARCHAR(14)
		, ISSIMPLIFIEDADDRESS_RU BIGINT
		, CHANNELREFERENCEID NVARCHAR(38)
		, SETTLEMENTRECID BIGINT
		, LOCALITYRECID BIGINT
		) AS r
GO

**Did this occur in prior versions?  If not - which version(s) did it work in?**
(DacFx/SqlPackage/SSMS/Azure Data Studio)

It is first time that i tried this. Extract and Publish to Synapse Serverless is a new Feature. 
See also https://github.com/microsoft/DacFx/issues/23

**Comment by llali** [comment] 2023-04-10 17:33
@SaschaProdware thanks for creating this issue. We recently fixed a bug when the value "{"READ_OPTIONS":["ALLOW_INCONSISTENT_READS"]" has extra space/extra line in it. I think the bug you are seeing is similar and it should be fixed already. To verify, you can remove any extra space or line from that option and if it works, you can be sure the issue is fixed in the next release of sqlpacakge.exe.

**Closed** 2023-08-15 20:04 UTC
Labels: bug, sqlserverless
