### ISSUE TITLE
Missing assembly type Microsoft.Data.SqlClient.Server.Format in Microsoft.Data.SqlClient, Version=5.0.0.0

### ISSUE THREAD

**Issue by TlotloS** [microsoft/DacFx#141] opened 2022-09-14 02:09 UTC
I'm attempting to create a new DacService object instance with the latest stable package installed (i.e. "v160.6161.0"), and I'm running on the .Net 6.0.

...Sadly I am met with these missing assembly type exceptions (TypeInitializationException) when attempting the create the construct the DacServices() object.

**Code snippet**
```
public string InitialiseDatabase(string dacpacRelativePath){

  var connectionString = "Data Source=(LocalDb)\\MSSQLLocalDB;Integrated Security=True";
  var instance = new DacServices(connectionString);

}
```

**StackTrace:**
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.SqlServer.Dac.DacServices' threw an exception.
  Source=Microsoft.SqlServer.Dac
  StackTrace:
   at Microsoft.SqlServer.Dac.DacServices..ctor(String connectionString)
   at B1Link.Audit.Tests.BasicTest.InitialiseDatabase(String dacpacRelativePath) in C:\..\..\B1NG-Service-Audit\B1Link.Audit.Tests\BasicTest.cs:line 44
   at B1Link.Audit.Tests.BasicTest..ctor() in C:\Users\Sebee\Development\B1 LINK MVP\B1NG-Service-Audit\B1Link.Audit.Tests\BasicTest.cs:line 24
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
TypeInitializationException: The type initializer for 'SqlSchemaModelStaticState' threw an exception.

Inner Exception 2:
TypeLoadException: Could not load type 'Microsoft.Data.SqlClient.Server.Format' from assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'.```

**Comment by ErikEJ** [comment] 2022-09-14 06:03
Duplicate of #126

**Comment by dzsquared** [comment] 2022-09-14 19:27
Item is duplicate to #126 - expected later this year.

**Closed** 2022-09-14 19:27 UTC
