### ISSUE TITLE
partitioned Table is always completely rebuild without reason

### ISSUE THREAD

**Issue by j-dc** [microsoft/DacFx#298] opened 2023-07-12 12:08 UTC
### versions
``` Powershell
sqlpackage /version
162.0.52.1
dotnet --version
7.0.305
get-content *.sqlproj | select-string '<sdk'
<Sdk Name="Microsoft.Build.Sql" Version="0.1.10-preview" />
``` 
Windows 11, Version 22H2, 10.0.22621

### steps to reproduce 
1. Create a sql project
2. Add a Partition function
```SQL
CREATE PARTITION FUNCTION [PF_TEST](DATETIME2 (2))
    AS RANGE LEFT
    FOR VALUES (
       '2023-01-01 00:00:00', '2023-02-01 00:00:00'
    );
```
3. Add a Partition Scheme
```SQL
CREATE PARTITION SCHEME [PS_TEST]
    AS PARTITION [PF_TEST]
    TO (		[PRIMARY],         [PRIMARY],         [PRIMARY]    );
```
4. Add a table using the partion
``` SQL
CREATE TABLE [dbo].[partitionTable] (
   [Timestamp]  DATETIME2 (2) NOT NULL
) on [PS_TEST] ([Timestamp])
```

5. build
 ``` powershell
dotnet build
```

6. Publish
``` Powershell
sqlpackage -action:Publish -sourcefile:"partitiontest.dacpac" -targetServername:'.' -targetdatabasename:"partitionstest" /TargetTrustServerCertificate:true /p:GenerateSmartDefaults='True'
```

7.Publish again
``` Powershell
sqlpackage -action:Publish -sourcefile:"partitiontest.dacpac" -targetServername:'.' -targetdatabasename:"partitionstest" /TargetTrustServerCertificate:true /p:GenerateSmartDefaults='True'
```
=> when publishing again right after the first publish, the table is completely rebuild.. twice.    The reason I partition a table is because it contains a huge amount of data. So the   INSERT INTO temp table takes forever and is unnecessary and unacceptable in production.

### steps to reproduce (EXAMPLE)
```Powershell
git clone https://github.com/j-dc/PartitionTest.git
cd PartitionTest
dotnet build
.\SCRIPTS\publishLocal.ps1
```

No working version found.

**Comment by j-dc** [comment] 2023-07-12 18:58
Workaround:    Create the partition function with dates in this format:  MDY  

I presume that this explains it?
```SQL
select dateformat from sys.syslanguages where name = @@LANGUAGE
```
In my case this returns:

|  | dateformat |
| --- | --- |
| 1 | mdy |


This is rather confusing, considering the value column of this query:
```SQL
select * from sys.partition_range_values
```

| function_id | boundary_id | parameter_id | value |
| --- | --- | --- | --- |
| 65541 | 1 | 1 | 2023-01-01 00:00:00.000 |
| 65541 | 2 | 1 | 2023-02-01 00:00:00.000 |

Here the dates are in a 'sortable' format.   This format has nothing to do with the defaults of my client/server.  So I presumed that using the 'sortable' format as returned by partition_range_values was the best, and easiest.   It wasn't.

This workaround result in this partition function  (altered datetime format):  

```SQL
CREATE PARTITION FUNCTION [PF_TEST](DATETIME2 (2))
    AS RANGE LEFT
    FOR VALUES (
       '1/1/2023 00:00:00', '2/1/2023 00:00:00'
    );
```


This remains a workaround.   Changing the SQL code so that the tooling is able to handle it always feels wrong. It's my opinion that tooling should be capable of handling all correct SQL code.

**Comment by agiBart** [comment] 2023-09-12 07:16
Unfortunaly above workaround does not seem to work for me.

select dateformat from sys.syslanguages where name = @@LANGUAGE
mdy

select * from sys.partition_range_values
65559	89	1	2023-09-11 00:00:00
65559	90	1	2023-09-18 00:00:00

CREATE PARTITION FUNCTION [WeeklyPartitionFunction](datetime2(6)) AS RANGE RIGHT
FOR VALUES (
'09-11-2023',
'09-18-2023')

every deploy still... :-(

azure sql database deployment log
....
2023-09-12T07:01:13.3394116Z Unbinding columns from changing objects on table [earniehistory].[loonbrieven]...
2023-09-12T07:01:15.9691006Z Caution: Changing any part of an object name could break scripts and stored procedures.
2023-09-12T07:01:15.9832630Z Dropping [WeeklyPartitionScheme]...
2023-09-12T07:01:16.2140437Z Dropping [WeeklyPartitionFunction]...
2023-09-12T07:01:16.2648162Z Creating [WeeklyPartitionFunction]...
2023-09-12T07:01:16.3040378Z Creating [WeeklyPartitionScheme]...
2023-09-12T07:01:16.3235515Z Partition scheme 'WeeklyPartitionScheme' has been created successfully. 'PRIMARY' is marked as the next used filegroup in partition scheme 'WeeklyPartitionScheme'.
2023-09-12T07:01:16.3388304Z Starting rebuilding table [earnieHistory].[boek_provisies]...
2023-09-12T07:01:18.0792567Z Caution: Changing any part of an object name could break scripts and stored procedures.
2023-09-12T07:01:18.0797346Z Caution: Changing any part of an object name could break scripts and stored procedures.
2023-09-12T07:01:18.1363183Z Creating [earniehistory].[boek_provisies].[IX_Modified_earniehistory_boek_provisies]...
......

**Comment by j-dc** [comment] 2023-09-18 10:51
Another possible workaround (not in all scenario's) is adding this parameters to the sqlpackage  cli:

    /p:ExcludeObjectType='PartitionFunctions' /p:ExcludeObjectType='PartitionSchemes'

This will ignore any changes made to partitions.

**Comment by takoau** [comment] 2023-10-17 03:18
> Another possible workaround (not in all scenario's) is adding this parameters to the sqlpackage  cli:
> 
> 
> 
>     /p:ExcludeObjectType='PartitionFunctions' /p:ExcludeObjectType='PartitionSchemes'
> 
> 
> 
> This will ignore any changes made to partitions.  

Doesn't work for my case.  My table is partitioned and with page compression.  /p:ExcludeObjectTypes=PartitionFunctions;PartitionSchemes still rebuilds the tables

**Comment by Mnior** [comment] 2023-12-14 17:45
```
<IgnoreFilegroupPlacement>True</IgnoreFilegroupPlacement>
<ExcludeObjectType>PartitionFunctions PartitionSchemes</ExcludeObjectType>
```
Adding keys to Publish.xml also does not help.

And with DeployReport, operations are also generated:
```
<Alert Name="DataMotion">
<Operation Name="Drop"><!-- some constraint if exists -->
<Operation Name="UnbindTable">
<Operation Name="Create"><!-- some indexes if exists -->
<Operation Name="TableRebuild">
```

**Comment by ssreerama** [comment] 2023-12-15 20:13
Hey @j-dc , I have tried to repro the issue by manually creating a project and also with your sample partitions project. I don't see any table re-creation with the re-publish. Did you happen to change the PF/PS after the publish? Would like to know if there are any additional steps required to repro the issue. Thanks

**Comment by j-dc** [comment] 2023-12-18 13:09
> Hey @j-dc , I have tried to repro the issue by manually creating a project and also with your sample partitions project. I don't see any table re-creation with the re-publish. Did you happen to change the PF/PS after the publish? Would like to know if there are any additional steps required to repro the issue. Thanks

considering previously given steps:  

git clone https://github.com/j-dc/PartitionTest.git
cd PartitionTest
dotnet build
.\SCRIPTS\publishLocal.ps1


The resulting change.sql for this steps looks like this: 
https://[raw.githubusercontent.com/j-dc/PartitionTest/master/SCRIPTS/changeScriptOnMySystem.sql](https://raw.githubusercontent.com/j-dc/PartitionTest/master/SCRIPTS/changeScriptOnMySystem.sql)

This file contains a very unwanted/unneeded   drop table.

The fact that you don't have it and I do, probably means we have different default server settings?
Could it be locale settings?
What extra information can I provide?

**Comment by ssreerama** [comment] 2023-12-18 16:54
@j-dc , can you check the same with the project in Visual studio and do right click and 'publish', and then right click on project again and do 'Generate Script'? does this process also giving the same result to you?

I'm using Visual studio 2022 and deployed the database on SQL server 2022, also used the SqlPackage version of 162.0.52.1 to publish and generate script manually.

**Comment by ssreerama** [comment] 2024-01-05 16:54
@j-dc , Do you have any update? Thanks

**Comment by ssreerama** [comment] 2024-07-17 18:39
We are still unable to repro the issue as mentioned, tested on couple of old versions too and unable to repro it. One way that the table rebuilds in this scenario when pf date values are diff, but DacFx already taking care of diff date formats and considers it as same value. Closing the issue and if one can produce us a repro, we can look into it. Thank you all.

**Closed by ssreerama** 2024-07-17 18:39 UTC
Labels: bug, need-more-info, P1

**Comment by AndreyShvidky** [comment] 2025-03-27 22:16
The issue is still not resolved and easily reploduced by code provided by topic starter.
Reproduced with VS 2022 17.13.4, SSDT 17.13.3.1
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\SqlPackage.exe" /version
162.6.15.1
But I'm not sure VS uses exactly that version while publishing. It can use some other installed and registered SqlPackage libraries.
dotnet --version
9.0.201

Steps:
Downgraded project compatibily level to SQL 2016 and published to Microsoft SQL Server 2016 (SP2-CU17) (KB5001092) - 13.0.5888.11 (X64) twice.
Second publishing, as expected, shows:
** User actions
     Drop
       [PF_TEST] (Partition Function)
     Create
       [PF_TEST] (Partition Function)

From my own experience: the only way to awoid recreation of PF with date ranges - is to provide date ranges in american datetime format, e.g. MDY 01/01/2021. And therefor, additional insruction required in PreDeploy to correctly deal with such ranges:
`set language us_english`
to awoid date mistreating by script executors.
