### ISSUE TITLE
Could not load file or assembly: Microsoft.Data.Tools.Schema.Sql.resources.dll

### ISSUE THREAD

**Issue by Phylum123** [microsoft/DacFx#148] opened 2022-09-26 20:53 UTC
I had visual studio open and the computer was restarted. After the restart, All deploy methods give me the error in the title. From what I understand, the English version of dacfx doesn't require *.resource.dll's.  What determines if resource dll's should be loaded? Any known fixes to this issue?

**Comment by llali** [comment] 2022-09-26 21:06
@Phylum123 would you please provide step by step to reproduce. Which version of Visual Studio are you using and which version of SQL Project extension?

**Comment by Phylum123** [comment] 2022-09-26 21:32
vs2022 - 17.3.4
dacfx - 160.6296.0 nuget package.

**Comment by Phylum123** [comment] 2022-09-27 15:04
I wouldn't know how to reprodduce. There is an issue with visual studio where if you performa arestart with a solution open, it can corrupt your projects/solution. This has happened to myself and other team members on a few occasions. Usually you can recover by upgrading your visual studio, it seems to correct whatever is happening. This time, upgrading resolved other issues, but not dacfx. I tried uninstalling and deleting the package folder for dacfx and then reinstalling and that didn't work. Is there some setting somewhere that tells it the language it is using, because it seems to want the main folder to have resource files, even  though in english you don't need it.

**Comment by llali** [comment] 2022-10-03 16:50
@Phylum123 have you created a [feedback ticket](https://developercommunity.visualstudio.com/home) for visual studio? if yes, can you please send the link here? 

For English .resource.dlls file are not needed as you mentioned. I tried to do the same thing (keep vs open and restart) but cannot repro the issue. I have a simple app that calls DacFx API to import/export/extract/publish. Should I try anything else?

Are you getting the dll at runtime or build time?

**Comment by llali** [comment] 2022-10-26 21:59
the app I'm using is really simple. I verified it targeting 4.7.2 and net6. I also tested different versions of DacFx Nuget. If you can please give me any details how to change my test to be able to repro what you are seeing:
DacServices service = new DacServices(connectionString);
            string dbName = "keep_AdventureWorks";

            string bacpacPackageFileName = "test.bacpac";
            Console.WriteLine("Exporting ... ");
            service.ExportBacpac(bacpacPackageFileName, dbName);
            Console.WriteLine("Export is done!");
            Console.WriteLine("Importing ... ");
            using (BacPackage package = BacPackage.Load(bacpacPackageFileName))
            {
                service.ImportBacpac(package, importedDbName);
            }
            Console.WriteLine("Import is done!");
            
            string dacpacPackageFileName = "test.dacpac";
            Console.WriteLine("Extracting ... ");
            service.Extract(dacpacPackageFileName, dbName, "test", new Version(1, 1));
            Console.WriteLine("Extract is done!");
            Console.WriteLine("Publishing ... ");
           
            using (DacPackage package = DacPackage.Load(dacpacPackageFileName))
            {
                service.Publish(package, deployDbName, new PublishOptions());
            }
            Console.WriteLine("Import is done!");

**Comment by llali** [comment] 2022-10-26 22:01
@Phylum123 is the other bug you created duplicate of this bug? https://github.com/microsoft/DacFx/issues/158 or can you repro it now even without restarting VS?

**Comment by Phylum123** [comment] 2022-11-03 20:10
I can repro without a restart. I just don't know what causes it. Like I Said I think it is getting confused as to what language it is set to or something... though, I did check my culture and it is - Canada - English.

**Comment by llali** [comment] 2023-08-15 20:10
close as no repro. please reopen with clear repro steps if still happens

**Closed by llali** 2023-08-15 20:10 UTC
