### ISSUE TITLE
Microsoft.Data.Tools.Schema.Sql.Deployment.DeploymentFailedException: The Element or Annotation class SqlIndex does not contain the Property class Online

### ISSUE THREAD

**Issue by jackliusr** [microsoft/DacFx#427] opened 2024-03-13 13:49 UTC
- SqlPackage or DacFx Version: 162.2.111.2
- .NET Framework (Windows-only) or .NET Core: 8.0.2
- Environment (local platform and source/target platforms): wsl2 + ubuntu22.04

**Steps to Reproduce:**

1. import a dacpac

(**DacFx/SqlPackage**/SSMS/Azure Data Studio)

**Comment by dzsquared** [comment] 2024-03-13 14:39
Can you share a bit more about how the dacpac was created?

**Comment by jackliusr** [comment] 2024-03-13 15:49
I run below command to build and get the dacpac file.
```bash
dotnet build ddd.sqlproj
```

ddd.sqlproj
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.15-preview" />
```

**Comment by ErikEJ** [comment] 2024-03-13 15:52
Please double check your sqlpackage version

**Comment by jackliusr** [comment] 2024-03-14 01:07
Below is the version info, command I used to get, and location of the sqlpackage.
```
jack@DIM-I-1HVZJR3:~$ sqlpackage /version
162.2.111.2
jack@DIM-I-1HVZJR3:~$ sqlpackage /version
162.2.111.2
jack@DIM-I-1HVZJR3:~$ which sqlpackage
/home/jack/.dotnet/tools/sqlpackage
jack@DIM-I-1HVZJR3:~$
```

**Comment by PaulVrugt** [comment] 2024-03-14 07:47
Running into the same issue. There is very little logging about what's actually going wrong

**Comment by Thomas386** [comment] 2024-03-14 12:49
Same issue: In the generated .dacpac file we now have a model.xml having with a property 'online' which causes the error message. Sample:
```
<Element Type="SqlIndex" Name="[dbo].[Core_Contact].[IX_Core_Contact]">
	<Property Name="Online" Value="False" />
	<Relationship Name="ColumnSpecifications">
		<Entry>
			<Element Type="SqlIndexedColumnSpecification">
				<Relationship Name="Column">
					<Entry>
						<References Name="[dbo].[Core_Contact].[Id]" />
					</Entry>
				</Relationship>
			</Element>
		</Entry>
		<Entry> etc.
```
If this line with the 'Online' property does not exist: No problem.	`

Using VS 17.9.3: This line exists.
Using VS 17.9.2: This line does not exist.

The line is written, if you define the index with the option 'ONLINE'. Sample:

```
CREATE NONCLUSTERED INDEX [IX_Core_Contact] ON [dbo].[Core_Contact]
(
    [Id] ASC,
    [Mandator_Id] ASC
)
INCLUDE ( [ShortName]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
```

**Comment by PaulVrugt** [comment] 2024-03-14 13:19
@Thomas386 great work sherlock. This will probably solve the issue for us. We have exactly 1 index in the project with the online property set

nevertheless, this should be fixed

**Comment by llali** [comment] 2024-03-14 18:00
@Thomas386 is the version of sqlpackage from AzurePipelin agent? This issue only happens if the version sqlpackage used to deploy is older than the version of dacfx used in SQLProject. can you confirm that you get the bug if you try to deploy locally ( not from Azure Pipeline) using sqlpcakge 162.2.111.2? Azure pipeline agents are usually have delay on updating to latest version of sqlpcakge.

**Comment by PaulVrugt** [comment] 2024-03-14 18:24
Isn't sql package update included in the visual studio updates? We started seeing the issue after updating visual studio on our own custom image for azure pipelines. Wouldn't this update both sqlproject and sqlpackage?

**Comment by jgillette** [comment] 2024-03-14 18:25
We had the same issue crop up today after we patched our build server's Visual Studio to the latest version. Updating our deployer to use the latest 162.2.111 SqlPackage fixed the issue.

**Comment by llali** [comment] 2024-03-14 18:40
@PaulVrugt when using Azure pipeline for deploy, the sqlpckage is coming from the agent not from Visual Studio and usually there's a delay between when we ship a new sqlpckage and when the agents get the update. VS also uses DacFx to build the project so in your case, you used DacFx 162.2 to build the project, because you updated VS but to deploy you are using 162.1 version of sqlpackge which is coming from Azure pipeline agent.

**Comment by JoshuaMillerNebraskablue** [comment] 2024-03-14 19:14
> We had the same issue crop up today after we patched our build server's Visual Studio to the latest version. Updating our deployer to use the latest 162.2.111 SqlPackage fixed the issue.

@jgillette - When you say upgraded the deployer, are you referring to the Azure DevOps build agent itself to the latest version?

**Comment by llali** [comment] 2024-03-14 20:01
if using azure pipeline and not using self-hosted agent, you can check the version of image picked by you pipeline and see if it matches the latest image here https://github.com/actions/runner-images?tab=readme-ov-file#faqs

**Comment by PaulVrugt** [comment] 2024-03-14 20:14
> @PaulVrugt when using Azure pipeline for deploy, the sqlpckage is coming from the agent not from Visual Studio and usually there's a delay between when we ship a new sqlpckage and when the agents get the update. VS also uses DacFx to build the project so in your case, you used DacFx 162.2 to build the project, because you updated VS but to deploy you are using 162.1 version of sqlpackge which is coming from Azure pipeline agent.

But we are using a private agent with the latest visual studio installed. We are not using hosted agents. There is no delay because there is only 1 thing (the agent image) to update. Apparently the latest vs update does not include an update of sqlpackage

**Comment by llali** [comment] 2024-03-14 20:16
@PaulVrugt are you using sqlpackage from VS location? would you please send the path? it's possible that you need to update sqlpackage using https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16 in your agent

**Comment by Thomas386** [comment] 2024-03-15 07:01
@llali : Thx for your help. -> We are on old versions and we will fix this now.

**Comment by PaulVrugt** [comment] 2024-03-15 08:28
We are using the `SqlAzureDacpacDeployment@1` in azure pipelines, which apparently uses the standalone version of sqlpackage in `C:\Program Files\Microsoft SQL Server\160\DAC\bin\SqlPackage.exe` and not the vs included one in:
`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\SqlPackage.exe`

this is where the issue occurs. It would have been a bit better if the vs included one was used. Anyway, we know the cause now

**Comment by PaulVrugt** [comment] 2024-03-18 16:19
> > We are using the `SqlAzureDacpacDeployment@1` in azure pipelines, which apparently uses the standalone version of sqlpackage in `C:\Program Files\Microsoft SQL Server\160\DAC\bin\SqlPackage.exe` and not the vs included one in: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\SqlPackage.exe`
> > this is where the issue occurs. It would have been a bit better if the vs included one was used. Anyway, we know the cause now
> 
> The reason why the step isn't able to pick up the sqlpackage.exe in the Visual Studio installation folder is probably located here: https://github.com/microsoft/azure-pipelines-extensions/blob/ae1eb2b556298beb949fc61e885e55fc18abed07/TaskModules/powershell/TaskModuleSqlUtility/SqlPackageOnTargetMachines.ps1#L327
> 
> Debugging this showed it is looking for the path: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\SqlPackage.exe\SqlPackage.exe`
> 
> I guess the folder structure has changed in any of the visual studio versions.

haha that simply looks like a bug. It's using the `SqlPackage.exe` double

**Comment by ErikEJ** [comment] 2024-03-18 16:22
I think the debugging conclusion is wrong.

**Comment by b3go** [comment] 2024-03-18 16:28
Well the part I posted is iterating through all elements in the DAC folder and appending sqlpackage.exe. There are no subfolders in the DAC folder for VS 2022. Which results in test-path calls for paths like the one I mentioned.

**Comment by ErikEJ** [comment] 2024-03-18 16:41
@b3go I see! It used to be in a number folder under the VS folder...

**Comment by ErikEJ** [comment] 2024-03-18 16:44
@dzsquared FYI! Do you take a PR to fix this?

**Comment by tpressleyhlr** [comment] 2024-03-19 18:49
We encountered this issue today with the latest version of the windows-latest VM. Updating our local release agents to use the newest version of sqlpackage resolved the issue.

**Comment by bheemvennapureddy** [comment] 2024-03-20 17:35
Pulling latest SQL package fixed this for us. Thanks

**Comment by dieterQBIT** [comment] 2024-03-21 12:24
That doens't seem to work for me. I updated to visual studio 17.9.4 and SqlPackage to 162.2.111 from https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16, but still getting the same error

**Comment by dieterQBIT** [comment] 2024-03-21 12:40
When I try to deploy to a database
![image](https://github.com/microsoft/DacFx/assets/96907676/a255eba9-9e2c-4684-b824-3e34fb55591b)

**Comment by dieterQBIT** [comment] 2024-03-21 12:45
sorry, project wasn't properly built. This is the error I get when trying to deploy
![image](https://github.com/microsoft/DacFx/assets/96907676/730ce9a7-1259-4af7-b6f5-0a0dfd77f8b8)

**Comment by dieterQBIT** [comment] 2024-03-21 12:48
I just noticed those older versions are also still installed. Should I remove them?
![image](https://github.com/microsoft/DacFx/assets/96907676/db5dddf5-8f37-4a6f-a89d-bed329db2e99)

**Comment by ErikEJ** [comment] 2024-03-21 12:58
@dieterQBIT Please share your deployment script/batch file, screenshots are not so helpful

**Comment by dieterQBIT** [comment] 2024-03-21 13:03
[EasyOffice.deploy_allowdataloss.zip](https://github.com/microsoft/DacFx/files/14695509/EasyOffice.deploy_allowdataloss.zip)

This worked perfectly until I updated to visual studio 17.9.3

**Comment by b3go** [comment] 2024-03-21 13:36
> That doens't seem to work for me. I updated to visual studio 17.9.4 and SqlPackage to 162.2.111 from https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16, but still getting the same error

Did you install using `dotnet tool install`? These are also not getting picked up by the PowerShell. You have to install using the `DacFramework.msi`

**Comment by b3go** [comment] 2024-03-21 13:41
Can you run the pipeline with diagnostics? It will show you which sqlpackage.exe is used.

**Comment by dieterQBIT** [comment] 2024-03-21 14:07
It shows `Running 64-bit SqlPackage Version 162.0.52.1 on .NET Core`
So where does it come from?

**Comment by ErikEJ** [comment] 2024-03-21 14:16
@dieterQBIT  .NET global tool?

Try to update with:

`dotnet tool update Microsoft.Sqlpackage -g`

**Comment by dieterQBIT** [comment] 2024-03-21 14:24
This works for me! Thanks a lot!

But how is this possible? I never used .NET Core before.

**Comment by ErikEJ** [comment] 2024-03-21 14:25
Someon or some app installed it

**Comment by dieterQBIT** [comment] 2024-03-21 14:29
strange...but again, thanks! case closed for me :-)

**Comment by williambuchanan2** [comment] 2024-03-21 23:08
Just started happening to us as well last night. For us it is happening in Azure Devops pipelines when deploying DB updates.

Not happening in Visual Studio on the latest version 17.9.4

**Comment by ErikEJ** [comment] 2024-03-22 05:54
@williambuchanan2 own agent or Microsoft hosted?

Can you share your task ?

**Comment by williambuchanan2** [comment] 2024-03-22 05:56
> @williambuchanan2 own agent or Microsoft hosted?
> 
> Can you share your task ?

Microsoft hosted. Had to remove all the "ONLINE =..." from our DB project to get it to deploy.

**Comment by ErikEJ** [comment] 2024-03-22 05:57
@williambuchanan2 can you share the task yaml snippet?

**Comment by williambuchanan2** [comment] 2024-03-22 06:01
> @williambuchanan2 can you share the task yaml snippet?

We aren't using yaml as such. We are using the "SQL Server database deploy" task, but here is the yaml from that:

variables:
  PDSDatabaseDacpac: '$(System.DefaultWorkingDirectory)/_Database ($(Release.EnvironmentName))/drop/Database/PDS.Database/bin/Release/PDS.Database.dacpac'
  DBServer: 'XXX'
  DBUsername: 'xxxx'
  DBPassword: 'xxxx'
  Args_Mining: '/v:xxx=xxxx /v:CustomerType=Mining /v:LegacyCardinalityEstimation=OFF'

steps:
- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName: Testing
  inputs:
    DacpacFile: '$(PDSDatabaseDacpac)'
    ServerName: '$(DBServer)'
    DatabaseName: XXXX
    AuthScheme: sqlServerAuthentication
    SqlUsername: '$(DBUsername)'
    SqlPassword: '$(DBPassword)'
    AdditionalArguments: '$(Args_Mining) /p:BlockOnPossibleDataLoss=false'

**Comment by ptoutant** [comment] 2024-03-25 15:04
Having same exact error.  I'm on VS 2022 17.9.4.  If I build with VS 2019 16.11.34, works fine.

**Comment by llali** [comment] 2024-03-25 15:09
closing this since it's not a dacfx bug

**Closed by llali** 2024-03-25 15:09 UTC

**Comment by dzsquared** [comment] 2024-03-25 15:20
**Resolution**
You may need to update SqlPackage on your pipeline agent -  https://learn.microsoft.com/sql/tools/sqlpackage/sqlpackage-download


**Other notes**
It looks like one of the ADO tasks is also not pulling SqlPackage from the correct location.  That repo is open to PRs, please feel free to tag me if you're able to jump in to correct before I get around to it. (https://github.com/microsoft/DacFx/issues/427#issuecomment-2004423545)

**Comment by ErikEJ** [comment] 2024-03-25 15:30
@d3go Interested in doing a PR to fix the AzDo task bug?

**Comment by ErikEJ** [comment] 2024-03-25 15:40
@dzsquared Happy to do a PR, but what version number should be returned for the dacFX under VS now that there is no folder with a version number? 999? Or open a .dll file in the folder an extract the number?

See the Get-SqlPackageOnTargetMachine method in https://github.com/microsoft/azure-pipelines-extensions/blob/master/TaskModules/powershell/TaskModuleSqlUtility/SqlPackageOnTargetMachines.ps1

**Comment by b3go** [comment] 2024-03-25 16:33
@ErikEJ I guess you meant me :D I could do a PR but I have the same question about the version number. Also the script seems to be unable to locate sqlpackage.exe if it was installed via `dotnet tool install`. Maybe it would be easier to just take it from an env var? Pipeline Task users could easily change it if they want to use another version.

Btw I opened an issue in the relevant repo https://github.com/microsoft/azure-pipelines-extensions/issues/1225

**Comment by ErikEJ** [comment] 2024-03-26 09:59
I did a PR https://github.com/microsoft/azure-pipelines-extensions/pull/1226

**Comment by jpomfret** [comment] 2024-04-02 17:56
Hey folks,
I'm struggling to work out what the issue is here in order to resolve it 😄 

I have a GitHub Action workflow failing with this error:
```
The Element or Annotation class SqlIndex does not contain the Property class Online.
At line:97891 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], Exception
    + FullyQualifiedErrorId : dbatools_Publish-DbaDacPackage
```

Reading through this conversation it seems like it's a mismatch in version of dacfx and sqlpackage.exe? However, I am using the `windows-latest` image for the runner, the [list of installed software](https://github.com/actions/runner-images/blob/win22/20240322.1/images/windows/Windows2022-Readme.md) states that this includes `DacFx 162.2.111.2` and I'm using the latest dbatools module (`Publish-DbaDacPackage`)  which has SqlPackage.exe version `162.2.111.2` 

![image](https://github.com/microsoft/DacFx/assets/981370/a754310b-9697-4c8a-a91f-2cf74b5cf21e)

I have tried to use the previous version of dbatools\dbatools.library but this gives me the same error. 

What am I missing? Thanks in advance!

**Comment by dzsquared** [comment] 2024-04-02 19:05
@jpomfret - if you add a script step that calls sqlpackage /version, does it return 162.2.111? 
Checking the dba tools code quick, I think it uses the msbuild nuget instead of sqlpackage itself - https://github.com/dataplat/dbatools/blob/86b3f3db92ab8f2f6ebab4259d47f7da158a748c/public/Publish-DbaDacPackage.ps1#L69
that nuget package is uh, not updated.

**Comment by ckrueger1979** [comment] 2024-05-14 06:47
This topic shouldn't be closed.
Visual Studio contains a new version of dacfx then https://aka.ms/dacfx-msi

I had to copy this directory for deployment:
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\
because I couldn't find a standalone download
