### ISSUE TITLE
Could not load file or assembly: Microsoft.Data.Tools.Schema.Sql.resources.dll

### ISSUE THREAD

**Issue by Phylum123** [microsoft/DacFx#158] opened 2022-10-24 15:24 UTC
- SqlPackage or DacFx Version: 160.6296.0
- .NET Framework (Windows-only) or .NET Core: .net 6.0
- Environment (local platform and source/target platforms): Windows 10

**Steps to Reproduce:**

1. Use DacServices.Deploy

I am using Microsoft.Data.SqlClient v4.1.1 and DacFx v160.6296.0

Below are the messages the deploy feeds back before failing: 
Initializing deployment
Analyzing deployment plan
Updating database
Creating deployment plan
Verifying deployment plan
Deploying package to database
Creating deployment plan
Initializing deployment
Message SQL73001: Initializing deployment (Start)

And then after a decently long pause, I get the error:
System.IO.FileNotFoundException: 'Could not load file or assembly: Microsoft.Data.Tools.Schema.Sql.resources.dll'

**Comment by Phylum123** [comment] 2022-10-24 17:56
I created a new project in the same solution, copied the code over from the old one. I then removed the Micorosft.Data.SqlClient dependency and have DacFx as my only NuGet reference and still get the same error.

**Comment by chlafreniere** [comment] 2022-10-26 15:23
This is a duplicate of #148. We'll be using that issue to track. Thanks for the new info @Phylum123!

**Closed** 2022-11-01 20:24 UTC
Labels: bug
