### ISSUE TITLE
SchemaComparisonResult fails every time.

### ISSUE THREAD

**Issue by Aldebaran91** [microsoft/DacFx#337] opened 2023-09-14 06:27 UTC
- SqlPackage or DacFx Version: Microsoft.SqlServer.DacFx (nuget-version: 162.0.52)
- .NET Framework (Windows-only) or .NET Core: .net 6.0.407 (x64)
- Environment (local platform and source/target platforms): Windows Server 2022

**Steps to Reproduce:**

1. Create console app with this code:
```
using Microsoft.SqlServer.Dac.Compare;
using Microsoft.SqlServer.Dac;
using Microsoft.Data.SqlClient;

namespace DACPAC
{
    internal class Program
    {
        static void Main(string[] args)
        {
            SqlConnectionStringBuilder sql1 = new SqlConnectionStringBuilder()
            {
                InitialCatalog = "YOUR_CATALOG",
                DataSource = "YOUR_DATASOURCE",
                IntegratedSecurity = true,
            };
            SqlConnectionStringBuilder sql2 = new SqlConnectionStringBuilder()
            {
                InitialCatalog = "YOUR_CATALOG",
                DataSource = "YOUR_DATASOURCE",
                IntegratedSecurity = true,
            };

            SchemaComparison scmp = new SchemaComparison(new SchemaCompareDatabaseEndpoint(sql1.ToString()), new SchemaCompareDatabaseEndpoint(sql2.ToString()));


            SchemaComparisonResult result = scmp.Compare();
        }
    }
}
```
![daxfx_bug_162 0 52](https://github.com/microsoft/DacFx/assets/15835472/c4ebb2fa-a7ca-4139-b1ec-29fdd1c21259)

3. Show at the result of the SchemaComparisonResult. The differences is everytime "null". There is a bug which makes it unusable.

**Did this occur in prior versions?  If not - which version(s) did it work in?**

It did work perfect with version Microsoft.SqlServer.DacFx.x64.150.5282.3. But this version has no "DoNotEvaluateSqlCmdVariables" fix if DACPAC files are used to compare with a database.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by JanakVakharia** [comment] 2023-09-27 04:06
Encountered the same problem. It appears it has something to do with https://techcommunity.microsoft.com/t5/azure-sql-blog/connection-security-improvements-in-sqlpackage-161/ba-p/3672758. Set the /TargetTrustServerCertificate to True and it works. Potentially because the default value for /TargetEncryptConnection is True.

**Comment by Aldebaran91** [comment] 2023-09-27 07:54
Can confirm changing TrustServerCertificate to "true" was the solution. Still I want a better error handling. If I got an "Certificate from server is not trusted" exception I would have changed it long time ago. Please update error handling.

**Comment by namangupta211** [comment] 2023-09-28 13:17
Thanks @JanakVakharia .
Hi @Aldebaran91, This is by design, after the last year security enhancements, we have to use /TargetTrustServerCertificate to the validate server. About the error handling part, we are managing the error exceptions, if in the code you shared, you use result.GetErrors(), you will be able to see the exact errors that logged while validating the source and target servers.
Thank you.

**Comment by namangupta211** [comment] 2023-09-28 19:19
closing this issue. Thank you!

**Closed by namangupta211** 2023-09-28 19:19 UTC
Labels: bug
